"""empty message

Revision ID: 1bf7e2095511
Revises: 327110fa7359
Create Date: 2023-03-09 07:45:21.577713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf7e2095511'
down_revision = '327110fa7359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.alter_column('file',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2083),
               existing_nullable=False)
        batch_op.alter_column('sample_file',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2083),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audios', schema=None) as batch_op:
        batch_op.alter_column('sample_file',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('file',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
