"""empty message

Revision ID: 23308d346421
Revises: 
Create Date: 2023-02-03 15:16:17.751856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23308d346421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
