"""empty message

Revision ID: 327110fa7359
Revises: 3e1822e0f731
Create Date: 2023-03-04 22:07:24.774777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327110fa7359'
down_revision = '3e1822e0f731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2083),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
