"""empty message

Revision ID: 8c63bb15cb3f
Revises: 1bf7e2095511
Create Date: 2023-04-08 09:20:25.751753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c63bb15cb3f'
down_revision = '1bf7e2095511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('who_should_read_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('who_should_read_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('who_should_read_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('best_quote', sa.String(length=255), nullable=True))

    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_column('sample_text')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('best_quote')
        batch_op.drop_column('who_should_read_3')
        batch_op.drop_column('who_should_read_2')
        batch_op.drop_column('who_should_read_1')

    # ### end Alembic commands ###
