"""empty message

Revision ID: b6e3db465188
Revises: b62f32d45004
Create Date: 2023-02-15 14:10:00.714904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e3db465188'
down_revision = 'b62f32d45004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('creator_ip', sa.String(length=15), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updater_ip', sa.String(length=15), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deletor_ip', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objects')
    # ### end Alembic commands ###
