"""empty message

Revision ID: fe5346dc8252
Revises: b6e3db465188
Create Date: 2023-02-15 14:22:17.286701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5346dc8252'
down_revision = 'b6e3db465188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.drop_column('original_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
